import random as rd
 
file = open("testDataPerf.h", 'w')
numTest = 3
clauses = 1000
maxVar = 100
numVar = 30

def gen(val, numVar):
    a = rd.randint(-val, val)
    if abs(a) > 10 and abs(a) == maxVar - numVar:
        a = (a / abs(a)) * numVar
    if a == 0:
        return 1
    return a

file.write("//this file was autogenerated\n")

def writeFile(file, maxVarGlob, numVar, i, globClauses):
    maxVar = rd.randint(2, maxVarGlob)
    clauses = rd.randint(globClauses - 100, globClauses)
    line = "constexpr int size_clauses" + str(i) + " = " + str(clauses) + ";"
    file.write(line)
    line = "\nconstexpr std::array<std::array<int, 3>, " + str(clauses) + "> input_clauses" + str(i) + " = {{"
    for i in range(clauses):
        if i == clauses - 1:
            line = line + "{" + str(gen(maxVar, numVar)) + ", " + str(gen(maxVar, numVar)) + ", " + str(gen(maxVar, numVar)) + "}}};\n"
        else:
            line = line + "{" + str(gen(maxVar, numVar)) + ", " + str(gen(maxVar, numVar)) + ", " + str(gen(maxVar, numVar)) + "}, "
    file.write(line)
    
i = 2
while i <= numTest:
    writeFile(file, maxVar, numVar, i, clauses)
    i = i + 1

file.close()