import random as rd
 
file = open("testDataBigClauses.h", 'w')
numTest = 12
clauses = 5000
maxVar = 10
numVar = 10

def gen(val):
    a = rd.randint(-val, val)
    if a == 0:
        return 1
    return a

file.write("//this file was autogenerated\n")

def writeFile(file, maxVarGlob, numVar, i, globClauses):
    maxVar = rd.randint(2, maxVarGlob)
    clauses = rd.randint(globClauses - 100, globClauses)
    line = "constexpr int size_clauses" + str(i) + " = " + str(clauses) + ";"
    file.write(line)
    line = "\nconstexpr std::array<std::array<int, 3>, " + str(clauses) + "> input_clauses" + str(i) + " = {{"
    for i in range(clauses):
        if i == clauses - 1:
            line = line + "{" + str(gen(maxVar)) + ", " + str(gen(maxVar)) + ", " + str(gen(maxVar)) + "}}};\n"
        else:
            line = line + "{" + str(gen(maxVar)) + ", " + str(gen(maxVar)) + ", " + str(gen(maxVar)) + "}, "
    file.write(line)
    
i = 2
while i <= numTest:
    writeFile(file, maxVar, numVar, i, clauses)
    i = i + 1

file.close()